# ===============================
# CONFIGURACIÓN DE BASE DE DATOS
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/control_asistencia
spring.datasource.username=postgres
spring.datasource.password=ares

# ===============================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===============================
# 'update' permite que Spring Boot cree las tablas si no existen sin borrar los datos existentes
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
file.upload-dir=uploads
# ===============================
# CONFIGURACIÓN DE SEGURIDAD (JWT)
# ===============================
# Clave secreta para firmar los tokens (esta es de ejemplo en caso de que no tengas una)
agro.app.jwtSecret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Duración de 1 día (en milisegundos)
agro.app.jwtExpirationMs=86400000


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ares19951208@gmail.com
spring.mail.password=ptbl mccj ylsf xkrq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.jpa.open-in-view=false