# ==============================================================
# CONFIGURACIÓN DE BASE DE DATOS (Soporta Local y Render)
# ==============================================================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/control_asistencia}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ares}

# ==============================================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ==============================================================
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==============================================================
# ARCHIVOS Y PUERTO
# ==============================================================
file.upload-dir=${FILE_UPLOAD_DIR:uploads}
server.port=${SERVER_PORT:8080}

# ==============================================================
# CONFIGURACIÓN DE SEGURIDAD (JWT)
# ==============================================================
agro.app.jwtSecret=${AGRO_APP_JWTSECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
agro.app.jwtExpirationMs=${AGRO_APP_JWTEXPIRATIONMS:86400000}

# ==============================================================
# CONFIGURACIÓN DE CORREO (SMTP Gmail)
# ==============================================================
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:ares19951208@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:ptbl mccj ylsf xkrq}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
