-- Generated by Odoo PG Modeler

DO $$ BEGIN
  ALTER TABLE "public"."attendance_records" ADD CONSTRAINT "fk_attendance_records_employee_id" FOREIGN KEY ("employee_id") REFERENCES "public"."employee"("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS "idx_attendance_records_employee_id" ON "public"."attendance_records"("employee_id");

DO $$ BEGIN
  ALTER TABLE "public"."document" ADD CONSTRAINT "fk_document_employee_id" FOREIGN KEY ("employee_id") REFERENCES "public"."employee"("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS "idx_document_employee_id" ON "public"."document"("employee_id");

DO $$ BEGIN
  ALTER TABLE "public"."employee" ADD CONSTRAINT "fk_employee_position_id" FOREIGN KEY ("position_id") REFERENCES "public"."work_positions"("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS "idx_employee_position_id" ON "public"."employee"("position_id");

DO $$ BEGIN
  ALTER TABLE "public"."employee" ADD CONSTRAINT "fk_employee_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS "idx_employee_user_id" ON "public"."employee"("user_id");

DO $$ BEGIN
  ALTER TABLE "public"."employee_requests" ADD CONSTRAINT "fk_employee_requests_employee_id" FOREIGN KEY ("employee_id") REFERENCES "public"."employee"("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS "idx_employee_requests_employee_id" ON "public"."employee_requests"("employee_id");

DO $$ BEGIN
  ALTER TABLE "public"."employee_requests" ADD CONSTRAINT "fk_employee_requests_manager_id" FOREIGN KEY ("manager_id") REFERENCES "public"."employee"("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS "idx_employee_requests_manager_id" ON "public"."employee_requests"("manager_id");

DO $$ BEGIN
  ALTER TABLE "public"."employee_requests" ADD CONSTRAINT "fk_employee_requests_request_type_id" FOREIGN KEY ("request_type_id") REFERENCES "public"."request_types"("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS "idx_employee_requests_request_type_id" ON "public"."employee_requests"("request_type_id");

DO $$ BEGIN
  ALTER TABLE "public"."employee_schedules" ADD CONSTRAINT "fk_employee_schedules_employee_id" FOREIGN KEY ("employee_id") REFERENCES "public"."employee"("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS "idx_employee_schedules_employee_id" ON "public"."employee_schedules"("employee_id");

DO $$ BEGIN
  ALTER TABLE "public"."employee_schedules" ADD CONSTRAINT "fk_employee_schedules_schedule_id" FOREIGN KEY ("schedule_id") REFERENCES "public"."work_schedules"("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS "idx_employee_schedules_schedule_id" ON "public"."employee_schedules"("schedule_id");

DO $$ BEGIN
  ALTER TABLE "public"."password_reset_tokens" ADD CONSTRAINT "fk_password_reset_tokens_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS "idx_password_reset_tokens_user_id" ON "public"."password_reset_tokens"("user_id");

DO $$ BEGIN
  ALTER TABLE "public"."payslips" ADD CONSTRAINT "fk_payslips_employee_id" FOREIGN KEY ("employee_id") REFERENCES "public"."employee"("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS "idx_payslips_employee_id" ON "public"."payslips"("employee_id");

DO $$ BEGIN
  ALTER TABLE "public"."users" ADD CONSTRAINT "fk_users_role_id" FOREIGN KEY ("role_id") REFERENCES "public"."roles"("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS "idx_users_role_id" ON "public"."users"("role_id");